### ISSUE TITLE
Have a functional ethernet setup on the nucleo-144 board (HIL)

### ISSUE THREAD

**Issue by HolgerStenberg** [IL2232-HT2022-HIL/SOFTWARE_DEV#10]

**Comment by HolgerStenberg** [comment]
The board uses the RMII interface type, will work on setting up the pins according to the datasheet

**Comment by HolgerStenberg** [comment]
We both need to configure the software in the micro controller and also configure the python script that is used to communicate with the HiL board. The goal is to get a valid ping back to the computer when it tries to contact the HiL-board.

**Comment by sofiecmf** [comment]
@matthiasthomasbecker you mentioned yesterday on the meeting that you had useful youtube videos that you had used for pinging the board. If you can find them, please link them here. :)

**Comment by HolgerStenberg** [comment]
Old task that is now resolved
