### ISSUE TITLE
HiL MCU: establish debugger functionality, printf to serial. USART probably.

### ISSUE THREAD

**Issue by olleblo** [IL2232-HT2022-HIL/SOFTWARE_DEV#27]
We need to be able to debug our programs that we run on the HiL-board. Printf can be done but we are yet not sure on exactly how.

_DONE WHEN:_ 
- [ ] Hardware setup for debug is done.
- [ ] We are able to do printf-statements in the code for HiL-board and see correct response on our computers.
- [ ] Document on wiki how to do this debugging functionality.

**Comment by sofiecmf** [comment]
https://embeddedarea.com/stm32-debugging-with-printf-by-using-swv-or-openocd/
