### ISSUE TITLE
Create python script able to communicate using ethernet

### ISSUE THREAD

**Issue by olleblo** [IL2232-HT2022-HIL/SOFTWARE_DEV#31]
We need to be able to have our python client to send and recieve over ethernet. A great idea would be to use first ping and then do echo functionality.

_DONE WHEN:_
- [x] Send ping from a python script. To HiL-board or other computer
- [x] Send a message from one python script and another script on another computer echoes said message. The echo should be presented correctly.

**Comment by Fkar97** [comment]
code in branch "echo-test"
