### ISSUE TITLE
Python: update HiL_client.py by adding communication functions

### ISSUE THREAD

**Issue by HolgerStenberg** [IL2232-HT2022-HIL/SOFTWARE_DEV#48]
In order to be able to send data to and from the client, the proposed uart prototype functions should be reviewed and merged to main

**Comment by Yuxiaowa** [comment]
The function for value transformation (e.g. encode 37.5 to a 16-bit number in the encoding process ) should also be writen and added.

**Comment by HolgerStenberg** [comment]
The functions for communication is in place and tested out
