### ISSUE TITLE
Python&Document: align python client scripts with its Wiki page

### ISSUE THREAD

**Issue by HolgerStenberg** [IL2232-HT2022-HIL/SOFTWARE_DEV#49]
- [x] align the function names in HiL_client.py
- [x] check the correctness of description and if the descriptions in wiki match the python scripts
- [x] fill in the documentation for the different client functions in the wiki page [python client function overview](https://github.com/IL2232-HT2022-HIL/SOFTWARE_DEV/wiki/PYTHON-CLIENT-FUNCTION-OVERVIEW)

**Comment by HolgerStenberg** [comment]
@Yuxiaowa Would you also be able to fill in the documentation for the different client functions in the wiki page [python client function overview?](https://github.com/IL2232-HT2022-HIL/SOFTWARE_DEV/wiki/PYTHON-CLIENT-FUNCTION-OVERVIEW)

**Comment by Yuxiaowa** [comment]
@HolgerStenberg Sure.

**Comment by HolgerStenberg** [comment]
Hi @Yuxiaowa!
Could you start fill in the documentation for the functions in [this wiki page?](https://github.com/IL2232-HT2022-HIL/SOFTWARE_DEV/wiki/PYTHON-CLIENT-FUNCTION-OVERVIEW). You can also try to see if the naming are all correct. I will keep on working on some decode functionality in the python client while you do this!

**Comment by Yuxiaowa** [comment]
@HolgerStenberg Sorry for the delay. I will work on this now.

**Comment by Yuxiaowa** [comment]
All of these three were finished.
